services:
  db:
    image: mysql:9.0.1
    container_name: mysql1
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ergon_graphos
    volumes:
      #      - ./mysql-data:/var/lib/mysql
      - ./ergon-graphos.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

# docker-compose up -d --build
# docker-compose exec -it db bash -c "mysql -proot"
# mysql -proot